### ISSUE TITLE
Regex pattern not working

### ISSUE THREAD

**Issue by manulachathurika** [ajclopez/mongo-spring-search#1]
Hi Antonio,

Thanks for your library. I tried it our and it's amazing. I found one issue. When I tried with the regex pattern it's not working.

phone=/^58/. When I tried with the regex like this it didn't give me the results. It's giving empty list rather providing the phone numbers starting from 58. I tried to debug and find the issue. But no luck. Could you please help me to resolved this issue.

Thanks !

**Comment by ajclopez** [comment]
Hi Manula,

Thank you for reporting the issue. I will fix the issue.

Thanks.

**Comment by manulachathurika** [comment]
Hi Antonio,

Thank you very much. Waiting for the fix. Appreciate your work.

Thanks !

**Comment by ajclopez** [comment]
Hi Manula,

I have released a new version [1.0.1](https://github.com/ajclopez/mongo-spring-search/releases/tag/1.0.1) to fix the use of regex pattern.

Let me know your comments.

Thank you for reporting the issue.

**Comment by manulachathurika** [comment]
Hi Antonio,

I tested the new version 1.0.1. The bug resolved and now I'm able to search from regex. Many thanks for the fix and I'm highly appreciate your work.

Thanks !
